#
# Lockstep Software Development Kit for Python
#
# (c) 2021-2022 Lockstep, Inc.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author     Ted Spence <tspence@lockstep.io>
# @copyright  2021-2022 Lockstep, Inc.
# @version    2021.39
# @link       https://github.com/Lockstep-Network/lockstep-sdk-python
#



from src.models.InvoiceAddressModel import InvoiceAddressModel
from src.models.InvoiceLineModel import InvoiceLineModel
from src.models.InvoicePaymentDetailModel import InvoicePaymentDetailModel
from src.models.NoteModel import NoteModel
from src.models.AttachmentModel import AttachmentModel
from src.models.CompanyModel import CompanyModel
from src.models.CompanyModel import CompanyModel
from src.models.ContactModel import ContactModel
from src.models.CreditMemoInvoiceModel import CreditMemoInvoiceModel
from src.models.CustomFieldValueModel import CustomFieldValueModel
from src.models.CustomFieldDefinitionModel import CustomFieldDefinitionModel

# An Invoice represents a bill sent from one company to another.  The creator of the invoice is identified
# by the `CompanyId` field, and the recipient of the invoice is identified by the `CustomerId` field.  Most
# invoices are uniquely identified both by a Lockstep Platform ID number and a customer ERP "key" that was
# generated by the system that originated the invoice.  Invoices have a total amount and a due date, and when
# some payments have been made on the Invoice the `TotalAmount` and the `OutstandingBalanceAmount` may be
# different.
class InvoiceModel:
    groupKey: str
    invoiceId: str
    companyId: str
    customerId: str
    erpKey: str
    purchaseOrderCode: str
    referenceCode: str
    salespersonCode: str
    salespersonName: str
    invoiceTypeCode: str
    invoiceStatusCode: str
    termsCode: str
    specialTerms: str
    currencyCode: str
    totalAmount: float
    salesTaxAmount: float
    discountAmount: float
    outstandingBalanceAmount: float
    invoiceDate: str
    discountDate: str
    postedDate: str
    invoiceClosedDate: str
    paymentDueDate: str
    importedDate: str
    primaryOriginAddressId: str
    primaryBillToAddressId: str
    primaryShipToAddressId: str
    created: str
    createdUserId: str
    modified: str
    modifiedUserId: str
    appEnrollmentId: str
    isVoided: bool
    inDispute: bool
    excludeFromAging: bool
    addresses: list[InvoiceAddressModel]
    lines: list[InvoiceLineModel]
    payments: list[InvoicePaymentDetailModel]
    notes: list[NoteModel]
    attachments: list[AttachmentModel]
    company: CompanyModel
    customer: CompanyModel
    customerPrimaryContact: ContactModel
    creditMemos: list[CreditMemoInvoiceModel]
    customFieldValues: list[CustomFieldValueModel]
    customFieldDefinitions: list[CustomFieldDefinitionModel]

